name: 'Gödel Task Router'
description: 'AI Code Review with Auto-Fix, Watermarking & Optimization. Free tier available.'
author: 'EpochCore Quantum - AWS Partner (S-0084812)'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  # Core Review
  mode:
    description: 'Review mode: quick, standard, deep'
    required: false
    default: 'standard'
  swarm-review:
    description: 'Enable 52-agent OpusSwarm AI review'
    required: false
    default: 'true'
  swarm-agents:
    description: 'Number of agents (2-52). Free: 8, Pro: 26, Enterprise: 52'
    required: false
    default: '8'

  # Auto-Fix Features (v3.0)
  auto-fix:
    description: '[FREE] Automatically fix security issues and code smells'
    required: false
    default: 'true'
  optimize:
    description: '[PRO] Apply code optimizations (var→const, remove console.log)'
    required: false
    default: 'false'
  compress:
    description: '[PRO] Generate minified versions of JS/CSS files'
    required: false
    default: 'false'
  watermark:
    description: '[PRO] Add quantum provenance watermarks to code files'
    required: false
    default: 'false'
  audit-deps:
    description: '[PRO] Audit and auto-fix vulnerable npm dependencies'
    required: false
    default: 'false'

  # Security Options
  signature-verify:
    description: 'Verify cryptographic signatures'
    required: false
    default: 'true'
  merkle-validate:
    description: 'Compute Merkle tree for file integrity'
    required: false
    default: 'true'
  fail-on-warning:
    description: 'Fail on warnings (not just errors)'
    required: false
    default: 'false'

  # Enterprise Options
  license-key:
    description: 'EpochCore license key for Pro ($29/mo) or Enterprise ($199/mo)'
    required: false
    default: ''
  worker-endpoint:
    description: 'Custom API endpoint (Enterprise)'
    required: false
    default: 'https://godel-task-router.com'

  # AWS Integration (Enterprise)
  aws-bedrock:
    description: '[ENTERPRISE] Use AWS Bedrock Claude 3 for AI review'
    required: false
    default: 'false'
  aws-bedrock-model:
    description: 'Bedrock model: claude-3-sonnet, claude-3-haiku'
    required: false
    default: 'claude-3-haiku'
  aws-security-hub:
    description: '[ENTERPRISE] Export findings to AWS Security Hub'
    required: false
    default: 'false'
  aws-region:
    description: 'AWS region for Bedrock/Security Hub'
    required: false
    default: 'us-east-1'

outputs:
  integrity-score:
    description: 'Overall integrity score (0-100)'
  auto-fixes:
    description: 'Number of auto-fixes applied'
  security-fixes:
    description: 'Security issues automatically fixed'
  compression-saved:
    description: 'Bytes saved via compression'
  watermarks-added:
    description: 'Files watermarked with provenance'
  swarm-consensus:
    description: 'AI swarm consensus score (0.0-1.0)'
  merkle-root:
    description: 'Merkle root hash of all files'
  report-url:
    description: 'URL to detailed report'

runs:
  using: 'node20'
  main: 'dist/index.js'

# QUANTUM_WATERMARK: GÖDEL_SEAL=40668c787c463ca5 V=3.0 ROUTER=true EPOCH=2026-01-09
