name: 'Gödel Code Review v3.0'
description: '52-Agent AI Code Review with Auto-Fix, Compression, Watermarking & Optimization. AWS Partner Verified.'
author: 'EpochCore Quantum - AWS Partner (S-0084812)'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  # Core Review
  mode:
    description: 'Review mode: quick, standard, deep'
    required: false
    default: 'standard'
  swarm-review:
    description: 'Enable 52-agent OpusSwarm AI review'
    required: false
    default: 'true'
  swarm-agents:
    description: 'Number of agents (2-52)'
    required: false
    default: '8'

  # NEW: Auto-Fix Features
  auto-fix:
    description: 'Automatically fix security issues and code smells'
    required: false
    default: 'true'
  optimize:
    description: 'Apply code optimizations (var→const, remove console.log, etc.)'
    required: false
    default: 'true'
  compress:
    description: 'Generate minified versions of JS/CSS files'
    required: false
    default: 'false'
  watermark:
    description: 'Add quantum provenance watermarks to code files'
    required: false
    default: 'true'
  audit-deps:
    description: 'Audit and auto-fix vulnerable npm dependencies'
    required: false
    default: 'true'

  # Security Options
  signature-verify:
    description: 'Verify cryptographic signatures'
    required: false
    default: 'true'
  merkle-validate:
    description: 'Compute Merkle tree for file integrity'
    required: false
    default: 'true'
  fail-on-warning:
    description: 'Fail on warnings (not just errors)'
    required: false
    default: 'false'

  # Enterprise Options
  license-key:
    description: 'EpochCore license key for Pro/Enterprise'
    required: false
    default: ''
  worker-endpoint:
    description: 'Custom API endpoint'
    required: false
    default: 'https://epochcore-unified-worker.epochcoreras.workers.dev'

  # AWS Integration
  aws-bedrock:
    description: 'Use AWS Bedrock for AI (requires AWS creds)'
    required: false
    default: 'false'
  aws-security-hub:
    description: 'Export findings to AWS Security Hub'
    required: false
    default: 'false'

outputs:
  integrity-score:
    description: 'Overall integrity score (0-100)'
  auto-fixes:
    description: 'Number of auto-fixes applied'
  security-fixes:
    description: 'Security issues automatically fixed'
  compression-saved:
    description: 'Bytes saved via compression'
  watermarks-added:
    description: 'Files watermarked with provenance'
  swarm-consensus:
    description: 'AI swarm consensus score (0.0-1.0)'
  merkle-root:
    description: 'Merkle root hash of all files'
  report-url:
    description: 'URL to detailed report'

runs:
  using: 'node20'
  main: 'dist/index.js'

# QUANTUM_WATERMARK: GÖDEL_SEAL=40668c787c463ca5 V=3.0 SWARM=52 EPOCH=2026-01-09
